### ISSUE TITLE
always-catch

### ISSUE THREAD

**Issue by gajus** [xjamundx/eslint-plugin-promise#1]
https://github.com/xjamundx/eslint-plugin-promise#always-catch

It is quiet rare that a promise chain itself would handle a failure. It is usually the top most promise node that must handle it, e.g. You wouldn't want your HTTP abstraction to fail the program. You'd want the program using the HTTP abstraction to handle whatever error arose.

Just an odd rule to have.

**Comment by xjamundx** [comment]
Thanks for the feedback. Several people on the main eslint repo explicitly asked for it and I think it comes down to it's probably useful for beginner/simple uses of promises where you're just `fetch(url).then(doSomething)` a lot. In those cases adding a `catch` anytime you use a `then` is probably pretty helpful, but definitely not very everyone though.

Do you have an example of where might use `then()` but not want `catch()`?

Some people also suggested it be modified to `return-or-catch`, so that you have to `catch` only if you're not returning the promise. Would that help make it more useful?

**Comment by gajus** [comment]
This was more of a open-ended question than tank specific-action issue. I was curious what is the original reason for introducing the rule. It makes sense in case of a simple code base that does not define an API but directly consume an already defined API.

**Comment by kosmotaur** [comment]
`return-or-catch` sounds like the dream! What I really aim at is not letting something error silently, rather than trying to handle errors in every module that wants to work with a promise.

**Comment by xjamundx** [comment]
Will work on this toray

**Comment by xjamundx** [comment]
lol it turns out that this already the default behavior, but i'll document it and add tests
